---
title: "Look at  the Smoothing params"
author: "Nick Isaac"
date: "18 June 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(reshape2)

source_dir <- '../models/15kit'
files <- list.files(source_dir)
```

## Extract model output
First gwe have to get ready

```{r prep model output}

smpars <- c('beta[1]','beta[2]',"taub")

# convert the file names to data
temp <- strsplit(gsub(files, pa=".rData", repl=""),"_")
metadata <- data.frame(raw = files, 
                       group=sapply(temp, function(x) x[[1]]),
                       knots=sapply(temp, function(x) x[[2]]),
                       scfac=sapply(temp, function(x) x[[3]]))

```

Now we can get the data out of the models

```{r extract model output}
output <- sapply(files, 
            simplify = FALSE,
            USE.NAMES = TRUE,
            function(modelfile){
              load(file.path(source_dir, modelfile)) # -> model
              x <- model$summary
              smoothpars <- x[dimnames(x)[[1]] %in% smpars,]
              out <- as.data.frame(smoothpars[,c(1,2,3,7,8)])
              out$param <- rownames(out)
              attr(out, 'n.iter') <- model$mcmc.info$n.iter           
              return(out)
            })

# first get the n.iter values out
n.iter <- sapply(output, function(m) attr(m, 'n.iter'))
mod_info <- data.frame(raw=names(n.iter), n.iter=n.iter, row.names=NULL)
mod_info <- merge(mod_info, metadata)[,-1]


# now manipulate the output in to a useful format
output <- melt(output, id=1:6)
output <- merge(output, metadata, by.x="L1", by.y='raw')[,-1]

output$precision <- 1/(output$sd^2)
output$width <- output[,"97.5%"] - output[,"2.5%"]

output$knots <- as.numeric(as.character(output$knots))
output$scfac <- as.numeric(as.character(output$scfac))

```

## Plot the results


```{r plot, echo=FALSE}
smp <- subset(output, param %in% smpars)
(qp <- qplot(y=width, x=factor(knots, ordered=TRUE), 
      data=smp, col=factor(scfac), shape=group) + 
  facet_wrap(~param, scales='free') +
  xlab('number of knots') +
  ylab('width of 95% credible intervals')
)

(qp <- qplot(y=Rhat, x=factor(knots, ordered=TRUE), 
      data=smp, col=factor(scfac), shape=group) + 
  facet_wrap(~param) +
  xlab('number of knots')
)
```

Check how many iterations this is based on

```{r mod_info}
unique(mod_info$n.iter)
```
